# Generated by Django 2.0.4 on 2018-04-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='definition',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
